name : CI-CD Pipeline
on :
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
